# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :demo do
    # add actions here: https://docs.fastlane.tools/actions
    build_ios_app()
#     firebase_app_distribution(
#             app: "1:932606192854:ios:8adeeba296f7ae4322ad77",
#             release_notes: "Demo",
#             groups:"Tester",
#             firebase_cli_token:"1//0eOj4k7v0tzlZCgYIARAAGA4SNwF-L9Irc3__dglEk90k0zR6jVKyvV-g9D8DB31iDTwX29wwbq3RNQFtatGIYVAueDXM8OLjMYk"
    )
  end
end